#!/bin/bash
# NEX QLoRA Fine-Tune — RunPod A100 Launch Script
# Generated by nex_finetune.py — UPDATED with merge + GGUF export
# Hardware target: A100 40GB or 80GB
# Base model: Qwen/Qwen2.5-3B-Instruct
# Output: nex_v5.gguf (Q4_K_M quantised, ready to run)

set -e
echo "=== NEX QLoRA Training + GGUF Export ==="
echo "GPU: $(nvidia-smi --query-gpu=name --format=csv,noheader)"
echo "VRAM: $(nvidia-smi --query-gpu=memory.total --format=csv,noheader)"

# ── STEP 1: Install dependencies ─────────────────────────────────────────────
echo ""
echo "--- Step 1: Installing dependencies ---"
pip install -q transformers peft trl datasets accelerate bitsandbytes
pip install -q sentencepiece protobuf

# ── STEP 2: QLoRA Training ───────────────────────────────────────────────────
echo ""
echo "--- Step 2: QLoRA Training ---"
python3 - << 'PYEOF'
import torch, json
from pathlib import Path
from datasets import Dataset
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
from peft import LoraConfig, get_peft_model, TaskType
from trl import SFTConfig, SFTTrainer

MODEL_ID   = "Qwen/Qwen3-8B"
TRAIN_FILE = "train.jsonl"
EVAL_FILE  = "eval.jsonl"
OUTPUT_DIR = "./nex_qwen_lora"

def load_jsonl(path):
    with open(path) as f:
        return [json.loads(l) for l in f if l.strip()]

train_raw = load_jsonl(TRAIN_FILE)
eval_raw  = load_jsonl(EVAL_FILE)

tok = AutoTokenizer.from_pretrained(MODEL_ID, trust_remote_code=True)
tok.pad_token = tok.eos_token

def format_example(ex):
    return tok.apply_chat_template(ex["messages"], tokenize=False, add_generation_prompt=False)

train_ds = Dataset.from_list([{"text": format_example(e)} for e in train_raw])
eval_ds  = Dataset.from_list([{"text": format_example(e)} for e in eval_raw])
print(f"Train: {len(train_ds)} | Eval: {len(eval_ds)}")

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_use_double_quant=True,
)
model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    quantization_config=bnb_config,
    device_map="auto",
    trust_remote_code=True,
)
model.config.use_cache = False

lora_cfg = LoraConfig(
    task_type=TaskType.CAUSAL_LM,
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    target_modules=["q_proj","k_proj","v_proj","o_proj","gate_proj","up_proj","down_proj"],
    bias="none",
)
model = get_peft_model(model, lora_cfg)
model.print_trainable_parameters()

training_args = SFTConfig(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=4,
    gradient_accumulation_steps=4,
    learning_rate=2e-4,
    bf16=True,
    logging_steps=10,
    eval_strategy="steps",
    eval_steps=50,
    save_strategy="epoch",
    warmup_ratio=0.03,
    lr_scheduler_type="cosine",
    report_to="none",
    dataset_text_field="text",
    max_seq_length=512,
)
trainer = SFTTrainer(
    model=model,
    args=training_args,
    train_dataset=train_ds,
    eval_dataset=eval_ds,
    processing_class=tok,
)
print("Starting training...")
trainer.train()
trainer.save_model(OUTPUT_DIR + "/final")
tok.save_pretrained(OUTPUT_DIR + "/final")
print(f"Training complete. LoRA saved to {OUTPUT_DIR}/final")
PYEOF

# ── STEP 3: Merge LoRA into base model ───────────────────────────────────────
echo ""
echo "--- Step 3: Merging LoRA into base model ---"
python3 - << 'MERGE'
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
from peft import PeftModel

MODEL_ID   = "Qwen/Qwen3-8B"
LORA_DIR   = "./nex_qwen_lora/final"
MERGED_DIR = "./nex_merged"

print(f"Loading base model: {MODEL_ID}")
base = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    torch_dtype=torch.float16,
    device_map="auto",
    trust_remote_code=True,
)
tok = AutoTokenizer.from_pretrained(LORA_DIR, trust_remote_code=True)

print(f"Loading LoRA adapter: {LORA_DIR}")
model = PeftModel.from_pretrained(base, LORA_DIR)

print("Merging LoRA weights into base model...")
model = model.merge_and_unload()

print(f"Saving merged model to {MERGED_DIR}")
model.save_pretrained(MERGED_DIR, safe_serialization=True)
tok.save_pretrained(MERGED_DIR)

print("Merge complete.")
print(f"Merged model size: {sum(p.numel() for p in model.parameters()) / 1e9:.2f}B params")
MERGE

# ── STEP 4: Convert to GGUF ───────────────────────────────────────────────────
echo ""
echo "--- Step 4: Converting to GGUF ---"

# Get llama.cpp for conversion
if [ ! -d "./llama.cpp" ]; then
    echo "Cloning llama.cpp..."
    git clone --depth 1 https://github.com/ggml-org/llama.cpp
fi

pip install -q gguf sentencepiece

echo "Converting to GGUF (F16)..."
python3 llama.cpp/convert_hf_to_gguf.py \
    ./nex_merged \
    --outfile ./nex_v5_f16.gguf \
    --outtype f16

echo "GGUF F16 conversion complete."
ls -lh ./nex_v5_f16.gguf

# ── STEP 5: Quantise to Q4_K_M ───────────────────────────────────────────────
echo ""
echo "--- Step 5: Quantising to Q4_K_M ---"

# Build llama-quantize
if [ ! -f "./llama.cpp/build/bin/llama-quantize" ]; then
    echo "Building llama.cpp quantizer..."
    cd llama.cpp
    cmake -B build -DGGML_CUDA=ON 2>/dev/null || cmake -B build
    cmake --build build --config Release -j$(nproc) --target llama-quantize
    cd ..
fi

echo "Quantising F16 → Q4_K_M..."
./llama.cpp/build/bin/llama-quantize \
    ./nex_v5_f16.gguf \
    ./nex_v5.gguf \
    Q4_K_M

echo ""
echo "=== COMPLETE ==="
ls -lh ./nex_v5.gguf ./nex_v5_f16.gguf 2>/dev/null

echo ""
echo "Download nex_v5.gguf — this is your new model (~1.8GB)"
echo "Drop it into /media/rr/NEX/llama.cpp/models/ and rename to nex_v5_q4km.gguf"
echo ""
echo "To download via RunPod:"
echo "  scp root@<pod-ip>:/workspace/nex_v5.gguf /media/rr/NEX/llama.cpp/models/nex_v5_q4km.gguf"
echo "Or use the RunPod file browser to download nex_v5.gguf"
